### PR TITLE
Fix availability checks in DDLog.m. Also fix memory leak. Fixes #995

### LINKED ISSUE #995: Memory Leak for macOS
in `DDLog.m`, there are some code for macos:
```
- (id)init {
    self = [super init];
    
    if (self) {
        self._loggers = [[NSMutableArray alloc] initWithCapacity:4];
        
#if TARGET_OS_IOS
        NSString *notificationName = @"UIApplicationWillTerminateNotification";
#else
        NSString *notificationName = nil;
        
        // On Command Line Tool apps AppKit may not be avaliable
#ifdef NSAppKitVersionNumber10_0
        
        if (NSApp) {
            notificationName = @"NSApplicationWillTerminateNotification";
        }
        
#endif
        
        if (!notificationName) {
            // If there is no NSApp -> we are running Command Line Tool app.
            // In this case terminate notification wouldn't be fired, so we use workaround.
            
            atexit_b (^{
                [self applicationWillTerminate:nil];
            });
        }
        
#endif /* if TARGET_OS_IOS */
        
```

There is a workaround:
```
            atexit_b (^{
                [self applicationWillTerminate:nil];
            });
```

It will cause DDLog will be retained and never be released. Right?

### PR DESCRIPTION
**Pull request by ffried**
### New Pull Request Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/CocoaLumberjack/CocoaLumberjack/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/CocoaLumberjack/)
* [x] I have searched for a similar pull request in the [project](https://github.com/CocoaLumberjack/CocoaLumberjack/pulls) and found none

* [x] I have updated this branch with the latest master to avoid conflicts (via merge from master or rebase)
* [x] I have added the required tests to prove the fix/feature I am adding
* [x] I have updated the documentation (if necessary)
* [x] I have run the tests and they pass
* [x] I have run the lint and it passes (`pod lib lint`)

This merge request fixes / refers to the following issues: #995 

### Pull Request Description

The availability checks in DDLog.m in `init` don't work anymore, because `NSAppKitVersionNumber10_0` is no longer a define.
This fixes this by checking for CLI tools with `DD_CLI` (which is used in other places) and `__has_include`.
Furthermore, the memory leak of custom DDLog objects captured in `atexit_b`.
And I've switched to use the constants provided by the frameworks for the notification names.

### CODE REVIEW

**Comment by OSSPolice** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          2 Warnings
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Any changes to library code should be reflected in the CHANGELOG. Please consider adding a note there about your change.</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">The library files were changed, but the tests remained unmodified. Consider updating or adding to the tests to match the library changes.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: Classes/DDLog.m [hunk 1]
```diff
@@ -180,24 +183,23 @@ - (id)init {
...
+            notificationName = NSApplicationWillTerminateNotification;
         }
-        
 #endif
-        
+
         if (!notificationName) {
             // If there is no NSApp -> we are running Command Line Tool app.
             // In this case terminate notification wouldn't be fired, so we use workaround.
+            __weak __auto_type weakSelf = self;
```
Comment (lolgear) [inline Classes/DDLog.m]: is `auto_type` allowed in framework?

Comment (ffried) [reply Classes/DDLog.m]: why wouldn't it?

Comment (lolgear) [reply Classes/DDLog.m]: It is rather new feature that was introduced in iOS 10 (as I remember?) and shipped with Xcode 8. Heh, I don't remember correct clang version.

Well, if so, what is a policy of backward compatibility for outdated clang versions which were introduced since deployment target version lower bound.

If framework supports versions down to iOS 8, should it also support Xcode version in which iOS 8 was introduced? ( but precisely clang and llvm versions that were shipped with Xcode 6)

Comment (rivera-ernesto) [reply Classes/DDLog.m]: I think Apple won't accept binaries build with older Xcode versions. Maybe that should be the Xcode compatibility policy.

Comment (ffried) [reply Classes/DDLog.m]: Yea, I'm with @rivera-ernesto on this one.
Also, I'm sure if someone runs into a problem with this, they'll open an issue... 😜

Comment (lolgear) [reply Classes/DDLog.m]: I have nice conversation about this feature with guy from Twitter. 
He said that this feature has "huge" impact on compilation time, especially for their codebase ( 1,5kk LoC ).

In my biggest project ( 200k LoC ) this feature doesn't have huge impact or any impact at all.

But..
If you start to "break one window", you should be consistent and break all windows by adding `__auto_type` for all pointers.

And here you will say "it is another PR" :) 
Or not?

**Comment by Whirlwind** [comment]
I am waiting this PR 👍

**Comment by rivera-ernesto** [comment]
Let's merge it already. We can always PR fixes (if needed) later on.

File: Classes/DDLog.m (hunk 1 above)
Comment (ffried) [reply Classes/DDLog.m]: Yea it would be another PR. Adding `__auto_type` doesn't fix #995 😉 
Also, for me this is something that can be added whenever a particular line is touched. Going through all source files just to add `__auto_type` doesn't seem to be worth the time. 😉
